--
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  remote_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  - { rolr: filebeat }
  - { role: metricbeat }
