---
filebeat_create_config: true

filebeat_prospectors:
  - input_type: log
    paths:
      - "/var/log/*.log"
      
filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "localhost:9200"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "0.0.0.0:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log
